// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/xopoww/wishes/restapi/apimodels"
)

// DeleteListItemsHandlerFunc turns a function with the right signature into a delete list items handler
type DeleteListItemsHandlerFunc func(DeleteListItemsParams, *apimodels.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteListItemsHandlerFunc) Handle(params DeleteListItemsParams, principal *apimodels.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteListItemsHandler interface for that can handle valid delete list items params
type DeleteListItemsHandler interface {
	Handle(DeleteListItemsParams, *apimodels.Principal) middleware.Responder
}

// NewDeleteListItems creates a new http.Handler for the delete list items operation
func NewDeleteListItems(ctx *middleware.Context, handler DeleteListItemsHandler) *DeleteListItems {
	return &DeleteListItems{Context: ctx, Handler: handler}
}

/*
	DeleteListItems swagger:route DELETE /lists/{id}/items deleteListItems

Delete items from existing list
*/
type DeleteListItems struct {
	Context *middleware.Context
	Handler DeleteListItemsHandler
}

func (o *DeleteListItems) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteListItemsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *apimodels.Principal
	if uprinc != nil {
		principal = uprinc.(*apimodels.Principal) // this is really a apimodels.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteListItemsInternalServerErrorBody delete list items internal server error body
//
// swagger:model DeleteListItemsInternalServerErrorBody
type DeleteListItemsInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`
}

// Validate validates this delete list items internal server error body
func (o *DeleteListItemsInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteListItemsInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("deleteListItemsInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete list items internal server error body based on context it is used
func (o *DeleteListItemsInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteListItemsInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteListItemsInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DeleteListItemsInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
