// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// DeleteItemTakenURL generates an URL for the delete item taken operation
type DeleteItemTakenURL struct {
	ID     int64
	ItemID int64

	AccessToken *string
	Rev         int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteItemTakenURL) WithBasePath(bp string) *DeleteItemTakenURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteItemTakenURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteItemTakenURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/lists/{id}/items/{item_id}/taken_by"

	id := swag.FormatInt64(o.ID)
	if id != "" {
		_path = strings.Replace(_path, "{id}", id, -1)
	} else {
		return nil, errors.New("id is required on DeleteItemTakenURL")
	}

	itemID := swag.FormatInt64(o.ItemID)
	if itemID != "" {
		_path = strings.Replace(_path, "{item_id}", itemID, -1)
	} else {
		return nil, errors.New("itemId is required on DeleteItemTakenURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var accessTokenQ string
	if o.AccessToken != nil {
		accessTokenQ = *o.AccessToken
	}
	if accessTokenQ != "" {
		qs.Set("accessToken", accessTokenQ)
	}

	revQ := swag.FormatInt64(o.Rev)
	if revQ != "" {
		qs.Set("rev", revQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteItemTakenURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteItemTakenURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteItemTakenURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteItemTakenURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteItemTakenURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteItemTakenURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
