// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteListOKCode is the HTTP code returned for type DeleteListOK
const DeleteListOKCode int = 200

/*
DeleteListOK Success

swagger:response deleteListOK
*/
type DeleteListOK struct {
}

// NewDeleteListOK creates DeleteListOK with default headers values
func NewDeleteListOK() *DeleteListOK {

	return &DeleteListOK{}
}

// WriteResponse to the client
func (o *DeleteListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteListForbiddenCode is the HTTP code returned for type DeleteListForbidden
const DeleteListForbiddenCode int = 403

/*
DeleteListForbidden Access denied

swagger:response deleteListForbidden
*/
type DeleteListForbidden struct {
}

// NewDeleteListForbidden creates DeleteListForbidden with default headers values
func NewDeleteListForbidden() *DeleteListForbidden {

	return &DeleteListForbidden{}
}

// WriteResponse to the client
func (o *DeleteListForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DeleteListNotFoundCode is the HTTP code returned for type DeleteListNotFound
const DeleteListNotFoundCode int = 404

/*
DeleteListNotFound List not found

swagger:response deleteListNotFound
*/
type DeleteListNotFound struct {
}

// NewDeleteListNotFound creates DeleteListNotFound with default headers values
func NewDeleteListNotFound() *DeleteListNotFound {

	return &DeleteListNotFound{}
}

// WriteResponse to the client
func (o *DeleteListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteListInternalServerErrorCode is the HTTP code returned for type DeleteListInternalServerError
const DeleteListInternalServerErrorCode int = 500

/*
DeleteListInternalServerError Server error

swagger:response deleteListInternalServerError
*/
type DeleteListInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *DeleteListInternalServerErrorBody `json:"body,omitempty"`
}

// NewDeleteListInternalServerError creates DeleteListInternalServerError with default headers values
func NewDeleteListInternalServerError() *DeleteListInternalServerError {

	return &DeleteListInternalServerError{}
}

// WithPayload adds the payload to the delete list internal server error response
func (o *DeleteListInternalServerError) WithPayload(payload *DeleteListInternalServerErrorBody) *DeleteListInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete list internal server error response
func (o *DeleteListInternalServerError) SetPayload(payload *DeleteListInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
