// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewDeleteItemTakenParams creates a new DeleteItemTakenParams object
//
// There are no default values defined in the spec.
func NewDeleteItemTakenParams() DeleteItemTakenParams {

	return DeleteItemTakenParams{}
}

// DeleteItemTakenParams contains all the bound params for the delete item taken operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteItemTaken
type DeleteItemTakenParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Optional access token for a list provided by list owner
	  In: query
	*/
	AccessToken *string
	/*
	  Required: true
	  In: path
	*/
	ID int64
	/*
	  Required: true
	  In: path
	*/
	ItemID int64
	/*
	  Required: true
	  In: query
	*/
	Rev int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteItemTakenParams() beforehand.
func (o *DeleteItemTakenParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAccessToken, qhkAccessToken, _ := qs.GetOK("accessToken")
	if err := o.bindAccessToken(qAccessToken, qhkAccessToken, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	rItemID, rhkItemID, _ := route.Params.GetOK("item_id")
	if err := o.bindItemID(rItemID, rhkItemID, route.Formats); err != nil {
		res = append(res, err)
	}

	qRev, qhkRev, _ := qs.GetOK("rev")
	if err := o.bindRev(qRev, qhkRev, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAccessToken binds and validates parameter AccessToken from query.
func (o *DeleteItemTakenParams) bindAccessToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.AccessToken = &raw

	return nil
}

// bindID binds and validates parameter ID from path.
func (o *DeleteItemTakenParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "path", "int64", raw)
	}
	o.ID = value

	return nil
}

// bindItemID binds and validates parameter ItemID from path.
func (o *DeleteItemTakenParams) bindItemID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("item_id", "path", "int64", raw)
	}
	o.ItemID = value

	return nil
}

// bindRev binds and validates parameter Rev from query.
func (o *DeleteItemTakenParams) bindRev(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("rev", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("rev", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("rev", "query", "int64", raw)
	}
	o.Rev = value

	return nil
}
