// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/xopoww/wishes/internal/models"
)

// DeleteListHandlerFunc turns a function with the right signature into a delete list handler
type DeleteListHandlerFunc func(DeleteListParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteListHandlerFunc) Handle(params DeleteListParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteListHandler interface for that can handle valid delete list params
type DeleteListHandler interface {
	Handle(DeleteListParams, *models.Principal) middleware.Responder
}

// NewDeleteList creates a new http.Handler for the delete list operation
func NewDeleteList(ctx *middleware.Context, handler DeleteListHandler) *DeleteList {
	return &DeleteList{Context: ctx, Handler: handler}
}

/*
	DeleteList swagger:route DELETE /lists/{id} deleteList

Delete existing list
*/
type DeleteList struct {
	Context *middleware.Context
	Handler DeleteListHandler
}

func (o *DeleteList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteListParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteListInternalServerErrorBody delete list internal server error body
//
// swagger:model DeleteListInternalServerErrorBody
type DeleteListInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`
}

// Validate validates this delete list internal server error body
func (o *DeleteListInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteListInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("deleteListInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete list internal server error body based on context it is used
func (o *DeleteListInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteListInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteListInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DeleteListInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
