// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/xopoww/wishes/restapi/apimodels"
)

// DeleteListItemsOKCode is the HTTP code returned for type DeleteListItemsOK
const DeleteListItemsOKCode int = 200

/*
DeleteListItemsOK Success

swagger:response deleteListItemsOK
*/
type DeleteListItemsOK struct {

	/*
	  In: Body
	*/
	Payload *apimodels.Revision `json:"body,omitempty"`
}

// NewDeleteListItemsOK creates DeleteListItemsOK with default headers values
func NewDeleteListItemsOK() *DeleteListItemsOK {

	return &DeleteListItemsOK{}
}

// WithPayload adds the payload to the delete list items o k response
func (o *DeleteListItemsOK) WithPayload(payload *apimodels.Revision) *DeleteListItemsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete list items o k response
func (o *DeleteListItemsOK) SetPayload(payload *apimodels.Revision) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteListItemsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteListItemsForbiddenCode is the HTTP code returned for type DeleteListItemsForbidden
const DeleteListItemsForbiddenCode int = 403

/*
DeleteListItemsForbidden Access denied

swagger:response deleteListItemsForbidden
*/
type DeleteListItemsForbidden struct {
}

// NewDeleteListItemsForbidden creates DeleteListItemsForbidden with default headers values
func NewDeleteListItemsForbidden() *DeleteListItemsForbidden {

	return &DeleteListItemsForbidden{}
}

// WriteResponse to the client
func (o *DeleteListItemsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DeleteListItemsNotFoundCode is the HTTP code returned for type DeleteListItemsNotFound
const DeleteListItemsNotFoundCode int = 404

/*
DeleteListItemsNotFound List not found

swagger:response deleteListItemsNotFound
*/
type DeleteListItemsNotFound struct {
}

// NewDeleteListItemsNotFound creates DeleteListItemsNotFound with default headers values
func NewDeleteListItemsNotFound() *DeleteListItemsNotFound {

	return &DeleteListItemsNotFound{}
}

// WriteResponse to the client
func (o *DeleteListItemsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteListItemsConflictCode is the HTTP code returned for type DeleteListItemsConflict
const DeleteListItemsConflictCode int = 409

/*
DeleteListItemsConflict Outdated revision

swagger:response deleteListItemsConflict
*/
type DeleteListItemsConflict struct {
}

// NewDeleteListItemsConflict creates DeleteListItemsConflict with default headers values
func NewDeleteListItemsConflict() *DeleteListItemsConflict {

	return &DeleteListItemsConflict{}
}

// WriteResponse to the client
func (o *DeleteListItemsConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// DeleteListItemsInternalServerErrorCode is the HTTP code returned for type DeleteListItemsInternalServerError
const DeleteListItemsInternalServerErrorCode int = 500

/*
DeleteListItemsInternalServerError Server error

swagger:response deleteListItemsInternalServerError
*/
type DeleteListItemsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *DeleteListItemsInternalServerErrorBody `json:"body,omitempty"`
}

// NewDeleteListItemsInternalServerError creates DeleteListItemsInternalServerError with default headers values
func NewDeleteListItemsInternalServerError() *DeleteListItemsInternalServerError {

	return &DeleteListItemsInternalServerError{}
}

// WithPayload adds the payload to the delete list items internal server error response
func (o *DeleteListItemsInternalServerError) WithPayload(payload *DeleteListItemsInternalServerErrorBody) *DeleteListItemsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete list items internal server error response
func (o *DeleteListItemsInternalServerError) SetPayload(payload *DeleteListItemsInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteListItemsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
