// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/xopoww/wishes/models"
)

// GetFooHandlerFunc turns a function with the right signature into a get foo handler
type GetFooHandlerFunc func(GetFooParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFooHandlerFunc) Handle(params GetFooParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetFooHandler interface for that can handle valid get foo params
type GetFooHandler interface {
	Handle(GetFooParams, *models.Principal) middleware.Responder
}

// NewGetFoo creates a new http.Handler for the get foo operation
func NewGetFoo(ctx *middleware.Context, handler GetFooHandler) *GetFoo {
	return &GetFoo{Context: ctx, Handler: handler}
}

/*
	GetFoo swagger:route GET /foo getFoo

Response with schema
*/
type GetFoo struct {
	Context *middleware.Context
	Handler GetFooHandler
}

func (o *GetFoo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFooParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
