// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/xopoww/wishes/models"
)

// GetListHandlerFunc turns a function with the right signature into a get list handler
type GetListHandlerFunc func(GetListParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetListHandlerFunc) Handle(params GetListParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetListHandler interface for that can handle valid get list params
type GetListHandler interface {
	Handle(GetListParams, *models.Principal) middleware.Responder
}

// NewGetList creates a new http.Handler for the get list operation
func NewGetList(ctx *middleware.Context, handler GetListHandler) *GetList {
	return &GetList{Context: ctx, Handler: handler}
}

/*
	GetList swagger:route GET /list getList

Get list info
*/
type GetList struct {
	Context *middleware.Context
	Handler GetListHandler
}

func (o *GetList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetListParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetListInternalServerErrorBody get list internal server error body
//
// swagger:model GetListInternalServerErrorBody
type GetListInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`
}

// Validate validates this get list internal server error body
func (o *GetListInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetListInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getListInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get list internal server error body based on context it is used
func (o *GetListInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetListInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetListInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetListInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
