// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetListTokenOKCode is the HTTP code returned for type GetListTokenOK
const GetListTokenOKCode int = 200

/*
GetListTokenOK Success

swagger:response getListTokenOK
*/
type GetListTokenOK struct {

	/*
	  In: Body
	*/
	Payload *GetListTokenOKBody `json:"body,omitempty"`
}

// NewGetListTokenOK creates GetListTokenOK with default headers values
func NewGetListTokenOK() *GetListTokenOK {

	return &GetListTokenOK{}
}

// WithPayload adds the payload to the get list token o k response
func (o *GetListTokenOK) WithPayload(payload *GetListTokenOKBody) *GetListTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get list token o k response
func (o *GetListTokenOK) SetPayload(payload *GetListTokenOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetListTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetListTokenForbiddenCode is the HTTP code returned for type GetListTokenForbidden
const GetListTokenForbiddenCode int = 403

/*
GetListTokenForbidden Access denied

swagger:response getListTokenForbidden
*/
type GetListTokenForbidden struct {
}

// NewGetListTokenForbidden creates GetListTokenForbidden with default headers values
func NewGetListTokenForbidden() *GetListTokenForbidden {

	return &GetListTokenForbidden{}
}

// WriteResponse to the client
func (o *GetListTokenForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetListTokenNotFoundCode is the HTTP code returned for type GetListTokenNotFound
const GetListTokenNotFoundCode int = 404

/*
GetListTokenNotFound List not found

swagger:response getListTokenNotFound
*/
type GetListTokenNotFound struct {
}

// NewGetListTokenNotFound creates GetListTokenNotFound with default headers values
func NewGetListTokenNotFound() *GetListTokenNotFound {

	return &GetListTokenNotFound{}
}

// WriteResponse to the client
func (o *GetListTokenNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetListTokenInternalServerErrorCode is the HTTP code returned for type GetListTokenInternalServerError
const GetListTokenInternalServerErrorCode int = 500

/*
GetListTokenInternalServerError Server error

swagger:response getListTokenInternalServerError
*/
type GetListTokenInternalServerError struct {
}

// NewGetListTokenInternalServerError creates GetListTokenInternalServerError with default headers values
func NewGetListTokenInternalServerError() *GetListTokenInternalServerError {

	return &GetListTokenInternalServerError{}
}

// WriteResponse to the client
func (o *GetListTokenInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
