// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/xopoww/wishes/restapi/apimodels"
)

// GetListItemsHandlerFunc turns a function with the right signature into a get list items handler
type GetListItemsHandlerFunc func(GetListItemsParams, *apimodels.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetListItemsHandlerFunc) Handle(params GetListItemsParams, principal *apimodels.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetListItemsHandler interface for that can handle valid get list items params
type GetListItemsHandler interface {
	Handle(GetListItemsParams, *apimodels.Principal) middleware.Responder
}

// NewGetListItems creates a new http.Handler for the get list items operation
func NewGetListItems(ctx *middleware.Context, handler GetListItemsHandler) *GetListItems {
	return &GetListItems{Context: ctx, Handler: handler}
}

/*
	GetListItems swagger:route GET /lists/{id}/items getListItems

Get list items
*/
type GetListItems struct {
	Context *middleware.Context
	Handler GetListItemsHandler
}

func (o *GetListItems) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetListItemsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *apimodels.Principal
	if uprinc != nil {
		principal = uprinc.(*apimodels.Principal) // this is really a apimodels.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetListItemsInternalServerErrorBody get list items internal server error body
//
// swagger:model GetListItemsInternalServerErrorBody
type GetListItemsInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`
}

// Validate validates this get list items internal server error body
func (o *GetListItemsInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetListItemsInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("getListItemsInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get list items internal server error body based on context it is used
func (o *GetListItemsInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetListItemsInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetListItemsInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetListItemsInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
