// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OAuthLoginHandlerFunc turns a function with the right signature into a o auth login handler
type OAuthLoginHandlerFunc func(OAuthLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn OAuthLoginHandlerFunc) Handle(params OAuthLoginParams) middleware.Responder {
	return fn(params)
}

// OAuthLoginHandler interface for that can handle valid o auth login params
type OAuthLoginHandler interface {
	Handle(OAuthLoginParams) middleware.Responder
}

// NewOAuthLogin creates a new http.Handler for the o auth login operation
func NewOAuthLogin(ctx *middleware.Context, handler OAuthLoginHandler) *OAuthLogin {
	return &OAuthLogin{Context: ctx, Handler: handler}
}

/*
	OAuthLogin swagger:route POST /oauth/login Auth oAuthLogin

Log in using OAuth token
*/
type OAuthLogin struct {
	Context *middleware.Context
	Handler OAuthLoginHandler
}

func (o *OAuthLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewOAuthLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// OAuthLoginOKBody o auth login o k body
//
// swagger:model OAuthLoginOKBody
type OAuthLoginOKBody struct {

	// token
	// Required: true
	Token *string `json:"token"`
}

// Validate validates this o auth login o k body
func (o *OAuthLoginOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *OAuthLoginOKBody) validateToken(formats strfmt.Registry) error {

	if err := validate.Required("oAuthLoginOK"+"."+"token", "body", o.Token); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this o auth login o k body based on context it is used
func (o *OAuthLoginOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *OAuthLoginOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *OAuthLoginOKBody) UnmarshalBinary(b []byte) error {
	var res OAuthLoginOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
