// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// OAuthLoginOKCode is the HTTP code returned for type OAuthLoginOK
const OAuthLoginOKCode int = 200

/*
OAuthLoginOK Success

swagger:response oAuthLoginOK
*/
type OAuthLoginOK struct {

	/*
	  In: Body
	*/
	Payload *OAuthLoginOKBody `json:"body,omitempty"`
}

// NewOAuthLoginOK creates OAuthLoginOK with default headers values
func NewOAuthLoginOK() *OAuthLoginOK {

	return &OAuthLoginOK{}
}

// WithPayload adds the payload to the o auth login o k response
func (o *OAuthLoginOK) WithPayload(payload *OAuthLoginOKBody) *OAuthLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the o auth login o k response
func (o *OAuthLoginOK) SetPayload(payload *OAuthLoginOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OAuthLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// OAuthLoginBadRequestCode is the HTTP code returned for type OAuthLoginBadRequest
const OAuthLoginBadRequestCode int = 400

/*
OAuthLoginBadRequest Invalid credentials

swagger:response oAuthLoginBadRequest
*/
type OAuthLoginBadRequest struct {
}

// NewOAuthLoginBadRequest creates OAuthLoginBadRequest with default headers values
func NewOAuthLoginBadRequest() *OAuthLoginBadRequest {

	return &OAuthLoginBadRequest{}
}

// WriteResponse to the client
func (o *OAuthLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// OAuthLoginNotFoundCode is the HTTP code returned for type OAuthLoginNotFound
const OAuthLoginNotFoundCode int = 404

/*
OAuthLoginNotFound User for OAuth token not found

swagger:response oAuthLoginNotFound
*/
type OAuthLoginNotFound struct {
}

// NewOAuthLoginNotFound creates OAuthLoginNotFound with default headers values
func NewOAuthLoginNotFound() *OAuthLoginNotFound {

	return &OAuthLoginNotFound{}
}

// WriteResponse to the client
func (o *OAuthLoginNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// OAuthLoginInternalServerErrorCode is the HTTP code returned for type OAuthLoginInternalServerError
const OAuthLoginInternalServerErrorCode int = 500

/*
OAuthLoginInternalServerError Server error

swagger:response oAuthLoginInternalServerError
*/
type OAuthLoginInternalServerError struct {
}

// NewOAuthLoginInternalServerError creates OAuthLoginInternalServerError with default headers values
func NewOAuthLoginInternalServerError() *OAuthLoginInternalServerError {

	return &OAuthLoginInternalServerError{}
}

// WriteResponse to the client
func (o *OAuthLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
