// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/xopoww/wishes/restapi/apimodels"
)

// PatchListHandlerFunc turns a function with the right signature into a patch list handler
type PatchListHandlerFunc func(PatchListParams, *apimodels.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchListHandlerFunc) Handle(params PatchListParams, principal *apimodels.Principal) middleware.Responder {
	return fn(params, principal)
}

// PatchListHandler interface for that can handle valid patch list params
type PatchListHandler interface {
	Handle(PatchListParams, *apimodels.Principal) middleware.Responder
}

// NewPatchList creates a new http.Handler for the patch list operation
func NewPatchList(ctx *middleware.Context, handler PatchListHandler) *PatchList {
	return &PatchList{Context: ctx, Handler: handler}
}

/*
	PatchList swagger:route PATCH /lists/{id} patchList

Edit existing list
*/
type PatchList struct {
	Context *middleware.Context
	Handler PatchListHandler
}

func (o *PatchList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchListParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *apimodels.Principal
	if uprinc != nil {
		principal = uprinc.(*apimodels.Principal) // this is really a apimodels.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PatchListInternalServerErrorBody patch list internal server error body
//
// swagger:model PatchListInternalServerErrorBody
type PatchListInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`
}

// Validate validates this patch list internal server error body
func (o *PatchListInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PatchListInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("patchListInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this patch list internal server error body based on context it is used
func (o *PatchListInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PatchListInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PatchListInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res PatchListInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
