// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchUserNoContentCode is the HTTP code returned for type PatchUserNoContent
const PatchUserNoContentCode int = 204

/*
PatchUserNoContent Success

swagger:response patchUserNoContent
*/
type PatchUserNoContent struct {
}

// NewPatchUserNoContent creates PatchUserNoContent with default headers values
func NewPatchUserNoContent() *PatchUserNoContent {

	return &PatchUserNoContent{}
}

// WriteResponse to the client
func (o *PatchUserNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PatchUserForbiddenCode is the HTTP code returned for type PatchUserForbidden
const PatchUserForbiddenCode int = 403

/*
PatchUserForbidden Access denied

swagger:response patchUserForbidden
*/
type PatchUserForbidden struct {
}

// NewPatchUserForbidden creates PatchUserForbidden with default headers values
func NewPatchUserForbidden() *PatchUserForbidden {

	return &PatchUserForbidden{}
}

// WriteResponse to the client
func (o *PatchUserForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PatchUserInternalServerErrorCode is the HTTP code returned for type PatchUserInternalServerError
const PatchUserInternalServerErrorCode int = 500

/*
PatchUserInternalServerError Server error

swagger:response patchUserInternalServerError
*/
type PatchUserInternalServerError struct {
}

// NewPatchUserInternalServerError creates PatchUserInternalServerError with default headers values
func NewPatchUserInternalServerError() *PatchUserInternalServerError {

	return &PatchUserInternalServerError{}
}

// WriteResponse to the client
func (o *PatchUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
