// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchListNoContentCode is the HTTP code returned for type PatchListNoContent
const PatchListNoContentCode int = 204

/*
PatchListNoContent Success

swagger:response patchListNoContent
*/
type PatchListNoContent struct {
}

// NewPatchListNoContent creates PatchListNoContent with default headers values
func NewPatchListNoContent() *PatchListNoContent {

	return &PatchListNoContent{}
}

// WriteResponse to the client
func (o *PatchListNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PatchListForbiddenCode is the HTTP code returned for type PatchListForbidden
const PatchListForbiddenCode int = 403

/*
PatchListForbidden Access denied

swagger:response patchListForbidden
*/
type PatchListForbidden struct {
}

// NewPatchListForbidden creates PatchListForbidden with default headers values
func NewPatchListForbidden() *PatchListForbidden {

	return &PatchListForbidden{}
}

// WriteResponse to the client
func (o *PatchListForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PatchListNotFoundCode is the HTTP code returned for type PatchListNotFound
const PatchListNotFoundCode int = 404

/*
PatchListNotFound List not found

swagger:response patchListNotFound
*/
type PatchListNotFound struct {
}

// NewPatchListNotFound creates PatchListNotFound with default headers values
func NewPatchListNotFound() *PatchListNotFound {

	return &PatchListNotFound{}
}

// WriteResponse to the client
func (o *PatchListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PatchListInternalServerErrorCode is the HTTP code returned for type PatchListInternalServerError
const PatchListInternalServerErrorCode int = 500

/*
PatchListInternalServerError Server error

swagger:response patchListInternalServerError
*/
type PatchListInternalServerError struct {
}

// NewPatchListInternalServerError creates PatchListInternalServerError with default headers values
func NewPatchListInternalServerError() *PatchListInternalServerError {

	return &PatchListInternalServerError{}
}

// WriteResponse to the client
func (o *PatchListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
