// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/xopoww/wishes/restapi/apimodels"
)

// PatchUserHandlerFunc turns a function with the right signature into a patch user handler
type PatchUserHandlerFunc func(PatchUserParams, *apimodels.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchUserHandlerFunc) Handle(params PatchUserParams, principal *apimodels.Principal) middleware.Responder {
	return fn(params, principal)
}

// PatchUserHandler interface for that can handle valid patch user params
type PatchUserHandler interface {
	Handle(PatchUserParams, *apimodels.Principal) middleware.Responder
}

// NewPatchUser creates a new http.Handler for the patch user operation
func NewPatchUser(ctx *middleware.Context, handler PatchUserHandler) *PatchUser {
	return &PatchUser{Context: ctx, Handler: handler}
}

/*
	PatchUser swagger:route PATCH /users/{id} Users patchUser

Edit user info
*/
type PatchUser struct {
	Context *middleware.Context
	Handler PatchUserHandler
}

func (o *PatchUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *apimodels.Principal
	if uprinc != nil {
		principal = uprinc.(*apimodels.Principal) // this is really a apimodels.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
