// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchUserOKCode is the HTTP code returned for type PatchUserOK
const PatchUserOKCode int = 200

/*
PatchUserOK Success

swagger:response patchUserOK
*/
type PatchUserOK struct {
}

// NewPatchUserOK creates PatchUserOK with default headers values
func NewPatchUserOK() *PatchUserOK {

	return &PatchUserOK{}
}

// WriteResponse to the client
func (o *PatchUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PatchUserForbiddenCode is the HTTP code returned for type PatchUserForbidden
const PatchUserForbiddenCode int = 403

/*
PatchUserForbidden Access denied

swagger:response patchUserForbidden
*/
type PatchUserForbidden struct {
}

// NewPatchUserForbidden creates PatchUserForbidden with default headers values
func NewPatchUserForbidden() *PatchUserForbidden {

	return &PatchUserForbidden{}
}

// WriteResponse to the client
func (o *PatchUserForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PatchUserNotFoundCode is the HTTP code returned for type PatchUserNotFound
const PatchUserNotFoundCode int = 404

/*
PatchUserNotFound User not found

swagger:response patchUserNotFound
*/
type PatchUserNotFound struct {
}

// NewPatchUserNotFound creates PatchUserNotFound with default headers values
func NewPatchUserNotFound() *PatchUserNotFound {

	return &PatchUserNotFound{}
}

// WriteResponse to the client
func (o *PatchUserNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PatchUserInternalServerErrorCode is the HTTP code returned for type PatchUserInternalServerError
const PatchUserInternalServerErrorCode int = 500

/*
PatchUserInternalServerError Server error

swagger:response patchUserInternalServerError
*/
type PatchUserInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PatchUserInternalServerErrorBody `json:"body,omitempty"`
}

// NewPatchUserInternalServerError creates PatchUserInternalServerError with default headers values
func NewPatchUserInternalServerError() *PatchUserInternalServerError {

	return &PatchUserInternalServerError{}
}

// WithPayload adds the payload to the patch user internal server error response
func (o *PatchUserInternalServerError) WithPayload(payload *PatchUserInternalServerErrorBody) *PatchUserInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch user internal server error response
func (o *PatchUserInternalServerError) SetPayload(payload *PatchUserInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
