// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/xopoww/wishes/models"
)

// PatchUserHandlerFunc turns a function with the right signature into a patch user handler
type PatchUserHandlerFunc func(PatchUserParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchUserHandlerFunc) Handle(params PatchUserParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PatchUserHandler interface for that can handle valid patch user params
type PatchUserHandler interface {
	Handle(PatchUserParams, *models.Principal) middleware.Responder
}

// NewPatchUser creates a new http.Handler for the patch user operation
func NewPatchUser(ctx *middleware.Context, handler PatchUserHandler) *PatchUser {
	return &PatchUser{Context: ctx, Handler: handler}
}

/*
	PatchUser swagger:route PATCH /user patchUser

Edit user info
*/
type PatchUser struct {
	Context *middleware.Context
	Handler PatchUserHandler
}

func (o *PatchUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PatchUserInternalServerErrorBody patch user internal server error body
//
// swagger:model PatchUserInternalServerErrorBody
type PatchUserInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`
}

// Validate validates this patch user internal server error body
func (o *PatchUserInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PatchUserInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("patchUserInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this patch user internal server error body based on context it is used
func (o *PatchUserInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PatchUserInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PatchUserInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res PatchUserInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
