// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/xopoww/wishes/models"
)

// PostListHandlerFunc turns a function with the right signature into a post list handler
type PostListHandlerFunc func(PostListParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostListHandlerFunc) Handle(params PostListParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostListHandler interface for that can handle valid post list params
type PostListHandler interface {
	Handle(PostListParams, *models.Principal) middleware.Responder
}

// NewPostList creates a new http.Handler for the post list operation
func NewPostList(ctx *middleware.Context, handler PostListHandler) *PostList {
	return &PostList{Context: ctx, Handler: handler}
}

/*
	PostList swagger:route POST /list postList

Create new list
*/
type PostList struct {
	Context *middleware.Context
	Handler PostListHandler
}

func (o *PostList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostListParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostListInternalServerErrorBody post list internal server error body
//
// swagger:model PostListInternalServerErrorBody
type PostListInternalServerErrorBody struct {

	// error
	// Required: true
	Error *string `json:"error"`
}

// Validate validates this post list internal server error body
func (o *PostListInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostListInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("postListInternalServerError"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post list internal server error body based on context it is used
func (o *PostListInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostListInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostListInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res PostListInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
