// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/xopoww/wishes/restapi/apimodels"
)

// PostListItemsCreatedCode is the HTTP code returned for type PostListItemsCreated
const PostListItemsCreatedCode int = 201

/*
PostListItemsCreated Success

swagger:response postListItemsCreated
*/
type PostListItemsCreated struct {

	/*
	  In: Body
	*/
	Payload *apimodels.Revision `json:"body,omitempty"`
}

// NewPostListItemsCreated creates PostListItemsCreated with default headers values
func NewPostListItemsCreated() *PostListItemsCreated {

	return &PostListItemsCreated{}
}

// WithPayload adds the payload to the post list items created response
func (o *PostListItemsCreated) WithPayload(payload *apimodels.Revision) *PostListItemsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post list items created response
func (o *PostListItemsCreated) SetPayload(payload *apimodels.Revision) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostListItemsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostListItemsForbiddenCode is the HTTP code returned for type PostListItemsForbidden
const PostListItemsForbiddenCode int = 403

/*
PostListItemsForbidden Access denied

swagger:response postListItemsForbidden
*/
type PostListItemsForbidden struct {
}

// NewPostListItemsForbidden creates PostListItemsForbidden with default headers values
func NewPostListItemsForbidden() *PostListItemsForbidden {

	return &PostListItemsForbidden{}
}

// WriteResponse to the client
func (o *PostListItemsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PostListItemsNotFoundCode is the HTTP code returned for type PostListItemsNotFound
const PostListItemsNotFoundCode int = 404

/*
PostListItemsNotFound List not found

swagger:response postListItemsNotFound
*/
type PostListItemsNotFound struct {
}

// NewPostListItemsNotFound creates PostListItemsNotFound with default headers values
func NewPostListItemsNotFound() *PostListItemsNotFound {

	return &PostListItemsNotFound{}
}

// WriteResponse to the client
func (o *PostListItemsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PostListItemsConflictCode is the HTTP code returned for type PostListItemsConflict
const PostListItemsConflictCode int = 409

/*
PostListItemsConflict Outdated revision

swagger:response postListItemsConflict
*/
type PostListItemsConflict struct {
}

// NewPostListItemsConflict creates PostListItemsConflict with default headers values
func NewPostListItemsConflict() *PostListItemsConflict {

	return &PostListItemsConflict{}
}

// WriteResponse to the client
func (o *PostListItemsConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

// PostListItemsInternalServerErrorCode is the HTTP code returned for type PostListItemsInternalServerError
const PostListItemsInternalServerErrorCode int = 500

/*
PostListItemsInternalServerError Server error

swagger:response postListItemsInternalServerError
*/
type PostListItemsInternalServerError struct {
}

// NewPostListItemsInternalServerError creates PostListItemsInternalServerError with default headers values
func NewPostListItemsInternalServerError() *PostListItemsInternalServerError {

	return &PostListItemsInternalServerError{}
}

// WriteResponse to the client
func (o *PostListItemsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
