// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/xopoww/wishes/models"
)

// PostListOKCode is the HTTP code returned for type PostListOK
const PostListOKCode int = 200

/*
PostListOK Success

swagger:response postListOK
*/
type PostListOK struct {

	/*
	  In: Body
	*/
	Payload *models.ID `json:"body,omitempty"`
}

// NewPostListOK creates PostListOK with default headers values
func NewPostListOK() *PostListOK {

	return &PostListOK{}
}

// WithPayload adds the payload to the post list o k response
func (o *PostListOK) WithPayload(payload *models.ID) *PostListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post list o k response
func (o *PostListOK) SetPayload(payload *models.ID) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostListInternalServerErrorCode is the HTTP code returned for type PostListInternalServerError
const PostListInternalServerErrorCode int = 500

/*
PostListInternalServerError Server error

swagger:response postListInternalServerError
*/
type PostListInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostListInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostListInternalServerError creates PostListInternalServerError with default headers values
func NewPostListInternalServerError() *PostListInternalServerError {

	return &PostListInternalServerError{}
}

// WithPayload adds the payload to the post list internal server error response
func (o *PostListInternalServerError) WithPayload(payload *PostListInternalServerErrorBody) *PostListInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post list internal server error response
func (o *PostListInternalServerError) SetPayload(payload *PostListInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
