// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Wishes API
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api
//	Version: 0.0.8
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
