// Code generated by go-swagger; DO NOT EDIT.

package apimodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OAuthCredentials o auth credentials
//
// swagger:model OAuthCredentials
type OAuthCredentials struct {

	// Textual ID of OAuth provider
	// Required: true
	ProviderID *string `json:"provider_id"`

	// OAuth bearer token
	// Required: true
	Token *string `json:"token"`
}

// Validate validates this o auth credentials
func (m *OAuthCredentials) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProviderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OAuthCredentials) validateProviderID(formats strfmt.Registry) error {

	if err := validate.Required("provider_id", "body", m.ProviderID); err != nil {
		return err
	}

	return nil
}

func (m *OAuthCredentials) validateToken(formats strfmt.Registry) error {

	if err := validate.Required("token", "body", m.Token); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this o auth credentials based on context it is used
func (m *OAuthCredentials) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OAuthCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OAuthCredentials) UnmarshalBinary(b []byte) error {
	var res OAuthCredentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
