// Code generated by go-swagger; DO NOT EDIT.

package apimodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// UserName user name
//
// swagger:model UserName
type UserName string

// Validate validates this user name
func (m UserName) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinLength("", "body", string(m), 3); err != nil {
		return err
	}

	if err := validate.MaxLength("", "body", string(m), 20); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this user name based on context it is used
func (m UserName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
